### PR TITLE
added new testing only tracks

### PR DESCRIPTION
**Pull request by Doge-God**

### CODE REVIEW

**Review by emilysteiner71 — COMMENTED** [review]
Hey Fu, can you please clarify which of the test tracks is for the "time trial race"? And will any of these be used for training? Cheers

**Comment by Doge-God** [comment]
> Hey Fu, can you please clarify which of the test tracks is for the "time trial race"? And will any of these be used for training? Cheers

multi_track_test_01.sdf contains 2 sets of tracks, each with 4 different width. This sdf shouldn't appear in any training.

**Comment by Doge-God** [comment]
Or would you like each track to have their own SDF?

**Comment by emilysteiner71** [comment]
In theory each "race" will be on only one track (although it would be worth testing on a couple of tracks) so if they could have individual sdfs that would be best, cheers

**Comment by Doge-God** [comment]
> In theory each "race" will be on only one track (although it would be worth testing on a couple of tracks) so if they could have individual sdfs that would be best, cheers

Should be all set now

**Review by emilysteiner71 — APPROVED** [review]

**Pull request merged**
